cache:
  zeromq:
    serverId: "test1"
    serverPort: 7000
  redis:
    databaseIndex: 2
  kafka:
    groupId: "mc"
    topic: "maxwell"
    host: "localhost"
    port: 9092
hikariMySQLProperties:
  enable: true
  jdbcUrl: "jdbc:mysql://数据库地址:数据库端口/数据库名称?useSSL=false&characterEncoding=UTF-8&autoReconnect=true"
  username: root
  password: password
  #获取连接的超时时间（毫秒）
  connectionTimeout: 5000
  #连接空闲超时时间（毫秒），空闲的连接在多久后会被关闭
  idleTimeout: 60000
  #连接最大生命周期（毫秒），默认为30分钟
  maxLifetime: 1800000
  #连接池中保持的最小空闲连接数
  minimumIdle: 1
  #连接池中允许的最大连接数
  maximumPoolSize: 10
redisPoolProperties:
  enable: true
  #数据库下标
  databaseIndex: 1
  host: "localhost"
  port: 6379
  #没有启用设置null即可
  user: null
  password: null
  #连接超时时间（毫秒），默认为 2000 毫秒
  timeout: 2000
  #连接池最大连接数，默认为 8
  maxTotal: 8
  #连接池最大空闲连接数，最大连接数的一半
  maxIdle: 4
  #连接池最小空闲连接数，默认为 1
  minIdle: 1
  #从连接池中获取连接时是否进行连接有效性检查
  testOnBorrow: false
  #归还连接到连接池时是否进行连接有效性检查
  testOnReturn: false
  #在空闲连接回收器线程运行时，是否对连接进行有效性检查
  testWhileIdle: false
  #空闲连接回收器线程运行的周期时间（毫秒），默认为 -1，表示不启用空闲连接回收器
  timeBetweenEvictionRunsMillis: 3600000
  #连接在连接池中保持空闲的最小时间（毫秒），超过这个时间的空闲连接将被回收
  minEvictableIdleTimeMillis: 1800000
